server:
  port: 8003
  servlet:
    context-path: /data_base-app
spring:
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
  datasource:
    path: classpath*:data.sql
    url: jdbc:postgresql://localhost:5432/testdb
    driver-class-name: org.postgresql.Driver
    username: sasha
    password: sasha
  sql:
    init:
      mode: always
