server:
  port: 8001
  servlet:
    context-path: /web-app
spring:
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:postgresql://localhost:5432/security
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  sql:
    init:
      mode: always
      data-locations: classpath*:security.sql
